// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDelkKRB5K5hi7iscvWUdPD028y3W0qE_4',
    appId: '1:370877420307:web:68613ba6bdc56c6c1d80e6',
    messagingSenderId: '370877420307',
    projectId: 'foviox-2f61b',
    authDomain: 'foviox-2f61b.firebaseapp.com',
    storageBucket: 'foviox-2f61b.firebasestorage.app',
    measurementId: 'G-GYKYF2PE4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT4qF6JSOUYIJX4q1-Evchm-B0IFR37zQ',
    appId: '1:370877420307:android:d726976ef4a5bc661d80e6',
    messagingSenderId: '370877420307',
    projectId: 'foviox-2f61b',
    storageBucket: 'foviox-2f61b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEGHFilB0p2TUyAoq4Jhk-SQTLY1x7Ovw',
    appId: '1:370877420307:ios:1ced4fd2477fb5221d80e6',
    messagingSenderId: '370877420307',
    projectId: 'foviox-2f61b',
    storageBucket: 'foviox-2f61b.firebasestorage.app',
    iosClientId: '370877420307-8b52ugj2tuqt008et66u42ss51vfgsau.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEGHFilB0p2TUyAoq4Jhk-SQTLY1x7Ovw',
    appId: '1:370877420307:ios:1ced4fd2477fb5221d80e6',
    messagingSenderId: '370877420307',
    projectId: 'foviox-2f61b',
    storageBucket: 'foviox-2f61b.firebasestorage.app',
    iosClientId: '370877420307-8b52ugj2tuqt008et66u42ss51vfgsau.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDelkKRB5K5hi7iscvWUdPD028y3W0qE_4',
    appId: '1:370877420307:web:840ad723e5d9029a1d80e6',
    messagingSenderId: '370877420307',
    projectId: 'foviox-2f61b',
    authDomain: 'foviox-2f61b.firebaseapp.com',
    storageBucket: 'foviox-2f61b.firebasestorage.app',
    measurementId: 'G-K32T01H6GK',
  );
}
