# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    if line =~ /FLUTTER_ROOT\s*=\s*(.*)/
      return $1.strip
    end
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}"
end

flutter_root = flutter_root

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  # Add your own pods here (e.g., 'pod 'GoogleSignIn'')
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    target.build_configurations.each do |config|
      # You can remove unused permissions here
      # e.g. to drop camera permissions:
      # config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
      #   '$(inherited)',
      #   'PERMISSION_CAMERA=0',
      # ]
    end
  end
end