platform :ios, '15.0'

ENV['COCOAPODS_DISABLE_SWIFT_PACKAGE_MANAGER'] = '1'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  pod 'GoogleSignIn'
  pod 'GoogleSignInSwift'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end